### PR TITLE
change Makefile for customary

### PR DESCRIPTION
**Pull request by charsyam**
I changed two points.
1. removing sc beluga bcc when calling make clean.
2. removing what directive, because many people expect
  just build with make alone

Thanks.

### CODE REVIEW

**Comment by mycoboco** [comment]
Thanks for your contribution. :-)

When I wrote `Makefile`, even if it looked a little nit-picky, my policy was to avoid GNU extensions and so to make it POSIX-compliant as much as possible. AFAICT, `.PHONY` does [not yet](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/make.html) seem to be adopted by POSIX.

Except that, I agree with other changes.
Could you take the `.PHONY` line out from your changes?

After your PR merged, I will drop all instances of the `what` target from other `Makefile`'s.

**Comment by mycoboco** [comment]
By the way, I've just found that `make` specified by POSIX has no support on `-C`. :-(

**Comment by charsyam** [comment]
@mycoboco I removed .PHONY 

thanks

**Comment by mycoboco** [comment]
Thanks!

**Pull request merged**
